### ISSUE TITLE
CardViews-Hintergrundfarben in richtiger Reihenfolge

### ISSUE THREAD

**Issue by NIPE-SYSTEMS** [GGDevelopers/SchulinfoAPP#24]
Dieser Issue ist ein Vorschlag.

Man könnte die (zurzeit noch) durcheinander angeordneten verschiedenen Farben der Cards (Vertretungsplan, Klausurenplan) in richtiger Reihenfolge anordnen, sodass sie einen abgestuften Farbverlauf bilden. Dafür könnte man die Startfarbe gelb und die Endfarbe rot nehmen, um den Design der Schule gerecht zu werden. Hier mal ein Beispiel von einer vorhandenen Todo-Listen-App:

![http://www.mobiflip.de/wp-content/uploads/2013/09/clear_header.jpg](http://www.mobiflip.de/wp-content/uploads/2013/09/clear_header.jpg)

Für die Sachsenwald-Schule könnte man die Farben von einem Hellblau bis zu einem Dunkelblau verwenden.

**Comment by asterix11** [comment]
Fixed.
